// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_normal_mode = "CgkI9Lat8aMREAIQAA"; // <GPGSID>
        public const string leaderboard_hard_mode = "CgkI9Lat8aMREAIQAQ"; // <GPGSID>
        public const string achievement_level_4_complete = "CgkI9Lat8aMREAIQBg"; // <GPGSID>
        public const string achievement_level_3_complete = "CgkI9Lat8aMREAIQBQ"; // <GPGSID>
        public const string achievement_level_2_complete = "CgkI9Lat8aMREAIQBA"; // <GPGSID>
        public const string achievement_level_1_complete = "CgkI9Lat8aMREAIQAw"; // <GPGSID>
        public const string achievement_level_5_complete = "CgkI9Lat8aMREAIQBw"; // <GPGSID>

}

